use fornecedores;

SELECT NOME, PREçO AS VALOR FROM PRODUTOS;

SELECT FORNECEDOR, count(*) FROM PRODUTOS_FORNECEDORES
GROUP BY FORNECEDOR;

SELECT f.NOME, COUNT(pf.PRODUTO)
FROM PRODUTOS_FORNECEDORES
JOIN FORNECEDORES f ON f.ID_FORNECEDOR =
pf.FORNECEDOR
GROUP BY f.NOME
;